### ISSUE TITLE
Calling "hyperdocs react" freezes.. Invalid regular expression Error

### ISSUE THREAD

**Issue by michaelwayman** [uesteibar/hyperdocs#11]
## Expected Behavior
`hyperdocs react` should take me to the react docs

## Current Behavior
The plugin hands and the developer tools says
```
Uncaught SyntaxError: Invalid regular expression: /(?<=hyperdocs).*/: Invalid group
    at /Users/me/.hyper_plugins/node_modules/hyperdocs/lib/index.js:67:54
```
## Possible Solution
Fix the regular expression

## Steps to Reproduce (for bugs)
Type `hyperdocs python` into terminal.

## Your Environment

- MacOS Sierra 10.12.4
- Hyper 1.4.8 (stable)

Plugins

- hyper-transparent (1.1.3),
- hyperterm-dibdabs (0.0.8),
- hyperterm-tabs (1.3.5),
- hyperlinks (0.5.0)
- hyper-alt-click (0.1.1),
- hyperterm-tabs (1.3.5),
- hyperdocs (1.1.3)

**Comment by uesteibar** [comment]
thanks @michaelwayman for reporting this! I'll look into it as soon as possible :)

**Comment by ryuheechul** [comment]
having the same issue and looking forward to get a patch!

**Comment by andretf** [comment]
`/(?<=hyperdocs).*/.exec(data)[0].split(']')[0].trim()`

`?<=` is not a valid Regular Expression for Javascript. I guess `hyperdocs` command had not being found before, therefore branch of code never been reached.

**Comment by uesteibar** [comment]
Thanks for having a look into this @andretf, will try to have a look next week and have a fix ready.

Sorry for the delay guys, I've been out for a while :)
